language: go
go: 1.12.x
sudo: true
services:
- docker
install: true
notifications:
  email: false
env:
  - GO111MODULE=on
script: 
  - make test
  - make build
after_success:
  - test -n "$TRAVIS_TAG" && make push
